config/routes.rb
Rails.application.routes.draw do
  get 'orders/index'
  root to: 'items#index'
  devise_for :users
  resources :items do
    resources :orders, only: [:index, :create]
    resources :favorites, only: [:create]
  end
  resources :users, only: [:show, :edit, :update, :destroy]
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  with_options presence: true do
    validates :nickname
    validates :last_name, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: 'is invalid. Input full-width characters.' }
    validates :first_name, format: { with: /\A[ぁ-んァ-ン一-龥]/, message: 'is invalid. Input full-width characters.' }
    validates :last_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: 'is invalid. Input full-width katakana characters.' }
    validates :first_name_kana, format: { with: /\A[ァ-ヶー－]+\z/, message: 'is invalid. Input full-width katakana characters.' }
    validates :birth_date
  end
  validates :password, format: { with: /\A(?=.*?[a-z])(?=.*?\d)[a-z\d]+\z/i, message: 'Include both letters and numbers' }, on: :create

  has_many :items, dependent: :destroy
  has_many :orders, dependent: :destroy
  has_many :favorites, dependent: :destroy
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user.id)
    else
      render :edit
    end
  end

  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to root_path
    else
      render :show
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :nickname, :last_name, :first_name, :last_name_kana, :first_name_kana, :birth_date)
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<%= render "shared/second-header"%>

<%= form_with model: @user, url: user_path(@user), class: 'registration-main', local: true do |f| %>
<div class='form-wrap'>
  <div class='form-header'>
    <h1 class='form-header-text'>
      会員情報入力
    </h1>
  </div>

  <%= render 'shared/error_messages', model: f.object %>

  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">ニックネーム</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.text_area :nickname, class:"input-default", id:"nickname", placeholder:"例) furima太郎", maxlength:"40" %>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">メールアドレス</label>
      <span class="indispensable">必須</span>
    </div>
    <%= f.email_field :email, class:"input-default", id:"email", placeholder:"PC・携帯どちらでも可", autofocus: true %>
  </div>
  
  <%# <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">パスワード</label>
      <span class="indispensable">必須</span>
    </div> %>
    <%# <%= f.password_field :password, class:"input-default", id:"password", placeholder:"6文字以上の半角英数字" %>
    <%# <p class='info-text'>※英字と数字の両方を含めて設定してください</p>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">パスワード(確認)</label>
      <span class="indispensable">必須</span>
    </div> %>
    <%# <%= f.password_field :password_confirmation, class:"input-default", id:"password-confirmation", placeholder:"同じパスワードを入力して下さい" %>
  <%# </div> %>

  <div class="form-group">
    <p class='form-info-header'>
      本人確認
    </p>
    <p class='form-info-text'>
      安心・安全にご利用いただくために、お客さまの本人情報の登録にご協力ください。他のお客さまに公開されることはありません。
    </p>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :last_name, class:"input-name", id:"last-name", placeholder:"例) 山田" %>
      <%= f.text_area :first_name, class:"input-name", id:"first-name", placeholder:"例) 陸太郎" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">お名前カナ(全角)</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-name-wrap'>
      <%= f.text_area :last_name_kana, class:"input-name", id:"last-name-kana", placeholder:"例) ヤマダ" %>
      <%= f.text_area :first_name_kana, class:"input-name", id:"first-name-kana", placeholder:"例) リクタロウ" %>
    </div>
  </div>
  <div class="form-group">
    <div class='form-text-wrap'>
      <label class="form-text">生年月日</label>
      <span class="indispensable">必須</span>
    </div>
    <div class='input-birth-wrap'>
      <%= raw sprintf(
                  f.date_select(
                    :birth_date,
                    class:'select-birth',
                    id:"birth-date",
                    use_month_numbers: true,
                    prompt:'--',
                    start_year: 1930,
                    end_year: (Time.now.year - 5),
                    date_separator: '%s'),
                  "<p> 年 </p>", "<p> 月 </p>") + "<p> 日 </p>" %>
    </div>
    <p class='info-text'>※ 本人情報は正しく入力してください。会員登録後、修正するにはお時間を頂く場合があります。</p>
  </div>
  <div class="form-group">
    <h2 class='form-bottom-text'>
      「会員登録」のボタンを押すことにより、
      <span>利用規約</span>
      <br>に同意したものとみなします
    </h2>
  </div>
  <div class='register-btn'>
    <%= f.submit "会員登録" ,class:"register-red-btn" %>
  </div>
  <p class='register-info'>本人情報の登録について</p>
</div>
<% end %>

<%= render "shared/second-footer"%>

app/views/users/show.html.erb
<%= render "shared/header" %>

<h1><%= @user.nickname %>さんのマイページ</h1>
<div class="user-info">
  <%= link_to "ユーザー情報の編集", edit_user_path %>
  <%= link_to "アカウントの削除", user_path(@user), method: :delete %>
</div>

<div class="user-item-index">
  <h2 class='title'><%= @user.nickname %>さんが出品した商品一覧</h2>
    <ul class='item-lists'>
      <%if @user.items.length != 0 %>
        <% @user.items.each do |item| %>
          <li class='list'>
            <%= link_to item_path(item) do %>
              <div class='item-img-content'>
              <%= image_tag item.image, class: "item-img" %>
              <% if item.order %>
                <div class='sold-out'>
                  <span>Sold Out!!</span>
                </div>
              <% end %>
              </div>
              <div class='item-info'>
                <h3 class='item-name'>
                <%= item.name %>
                </h3>
                <div class='item-price'>
                  <span><%= item.price %>円<br><%= item.shopping_fee_status[:name] %></span>
                </div>
                <div class='star-btn'>
                  <% if user_signed_in? && Favorite.find_by(user_id: current_user.id, item_id: item.id) %> 
                    <i class="fas fa-star"></i>
                  <% else %>
                    <i class="far fa-star"></i>
                  <% end %>
                  <span class='star-count'><%= item.favorites.length %></span>
                </div>
              </div>
            <% end %>
          </li>
        <% end %> 
      <% else %>
        <p>出品された商品はありません</p>
      <% end %>
    </ul>
</div>

<div class="user-fav-item">
  <h2 class='title'><%= @user.nickname %>さんのお気に入り商品一覧</h2>
    <ul class='item-lists'>
      <%if @user.favorites.length != 0 %>
        <% @user.favorites.each do |favorite| %>
          <li class='list'>
            <%= link_to item_path(favorite.item) do %>
              <div class='item-img-content'>
              <%= image_tag favorite.item.image, class: "item-img" %>
                <% if favorite.item.order %>
                  <div class='sold-out'>
                    <span>Sold Out!!</span>
                  </div>
                <% end %>
              </div>
              <div class='item-info'>
                <h3 class='item-name'>
                <%= favorite.item.name %>
                </h3>
                <div class='item-price'>
                  <span><%= favorite.item.price %>円<br><%= favorite.item.shopping_fee_status[:name] %></span>
                </div>
                <div class='star-btn'>
                  <% if user_signed_in? && Favorite.find_by(user_id: current_user.id, item_id: favorite.item_id) %> 
                    <i class="fas fa-star"></i>
                  <% else %>
                    <i class="far fa-star"></i>
                  <% end %>
                  <span class='star-count'><%= favorite.item.favorites.length %></span>
                </div>
              </div>
            <% end %>
          </li>
        <% end %> 
      <% else %>
        <p>出品された商品はありません</p>
      <% end %>
    </ul>
</div>

<%= render "shared/footer" %>